sudo: required

services:
  - docker

language: bash

before_install:
  - mkdir -p $HOME/bin
  - curl -L https://github.com/openshift/source-to-image/releases/download/v1.1.2/source-to-image-v1.1.2-5732fdd-linux-amd64.tar.gz | tar xzv -C $HOME/bin

script:
  - make test VERSION=gradle-2.6
